Создал план разработки
Tauders/dratuIT pull request #1
Opened 2021-05-10 11:33 UTC by morgunovdv

2021-05-10 11:34 UTC, Tauders requested changes
Очень интересно, ничего не понятно

2021-05-10 11:38 UTC, Tauders requested changes

2021-05-10 11:38 UTC, Tauders commented on task-1/Plan.md
> +d.	Список фигур (десериализация)
Список сливается в одну строку

2021-05-12 07:37 UTC, Tauders requested changes

2021-05-12 07:37 UTC, Tauders commented on task-1/Plan.md
> +
Зачем так много пустых строк?

2021-05-12 07:37 UTC, Tauders commented on task-1/Plan.md
> +	- Преобразование объектов класса в текстовое преобразование(Сериализация)
Пробел перед `(`

2021-05-12 07:37 UTC, Tauders commented on task-1/Plan.md
> +#       План разработки
Не используй табы, используй пробелы

2021-05-12 16:16 UTC, CodingFeles requested changes
Подпункты должны быть вложенными списками, а не на одном уровне с основной нумерацией.

2021-05-13 14:22 UTC, Tauders approved these changes

2021-05-13 14:24 UTC, CodingFeles approved these changes

2021-05-13 14:25 UTC, merged