[Subtask -2] Решение задачи
Tauders/dratuIT pull request #23
Opened 2021-11-17 16:12 UTC by morgunovdv

2021-11-18 11:02 UTC, CodingFeles requested changes
Хорошо!
Основа решения есть. Теперь надо поправить недочёты и заняться особыми случаями.

2021-11-18 11:02 UTC, CodingFeles commented on Subtasks/Denis/Subtask-2/Program.cs
> +            int Actions(string action, List<int> volumes)
1)  Си шарп позволяет описывать вложенные функции. Для этого есть своё применение, но пока лучше игнорировать этот случай и не делать их вложенными. Вынеси функцию из функции Main в класс Program.
2) Название функций должно быть глаголом. Это действие. Что тут делается?

2021-11-18 11:02 UTC, CodingFeles commented on Subtasks/Denis/Subtask-2/Program.cs
> +                        result /= volumes[i];
В этом кейсе есть один исключительный случай.

2021-11-18 11:02 UTC, CodingFeles commented on Subtasks/Denis/Subtask-2/Program.cs
> +                numbers[i] = rnd.Next(1, 10);
Не соответствует условиям задачи.

2021-11-18 11:02 UTC, CodingFeles commented on Subtasks/Denis/Subtask-2/Program.cs
> +            List<int> volumes = new List<int>();
Volumes? Тома? Объёмы? Я не очень понимаю имя этой переменной в данном контексте.

2021-11-18 11:02 UTC, CodingFeles commented on Subtasks/Denis/Subtask-2/Program.cs
> +                int counter = 0;
Что делает этот "счётчик" ?

2021-11-18 11:02 UTC, CodingFeles commented on Subtasks/Denis/Subtask-2/Program.cs
> +                if ((Int32.TryParse(input, out index)) & (index < numbers.Length))
Здесь есть исключительный случай.

2021-11-18 11:02 UTC, CodingFeles commented on Subtasks/Denis/Subtask-2/Program.cs
> +                        Console.WriteLine("Вы выбрали все числа из списка");
А если я для массива из 5 чисел,  введу 5 раз индекс 0 ?

2021-11-18 11:02 UTC, CodingFeles commented on Subtasks/Denis/Subtask-2/Program.cs
> +                    Console.WriteLine("Не корректный ввод");
Опечатка. "Некорректный".

2021-11-18 11:02 UTC, CodingFeles commented on Subtasks/Denis/Subtask-2/Program.cs
> +                else
Тут и выше: не делай разрыв строк перед else.

2021-11-18 11:02 UTC, CodingFeles commented on Subtasks/Denis/Subtask-2/Program.cs
> +                else
И ниже тоже :)

2021-11-18 18:13 UTC, Tauders requested changes

2021-11-18 18:13 UTC, Tauders commented on Subtasks/Denis/Subtask-2/Program.cs
> +            if (action == "+")
Используй switch-case

2021-11-18 18:13 UTC, Tauders commented on Subtasks/Denis/Subtask-2/Program.cs
> +        public static int GetAction(string action, List<int> valuesOfNumbers)
Что делает эта функция? Почему так называется?

2021-11-18 18:13 UTC, Tauders commented on Subtasks/Denis/Subtask-2/Program.cs
> +            Console.Write($"Числа введены, выберите доступные: ");
Сделай как в примере, это после вывода чисел.

2021-11-18 18:13 UTC, Tauders commented on Subtasks/Denis/Subtask-2/Program.cs
> +                if ((Int32.TryParse(input, out index)) & (index < numbers.Length))
"&" - побитовая операция, используй "&&", почитай в чём разница.

2021-11-18 18:13 UTC, Tauders commented on Subtasks/Denis/Subtask-2/Program.cs
> +            int index = 0;
Зачем это за пределами цикла?

2021-11-18 18:13 UTC, Tauders commented on Subtasks/Denis/Subtask-2/Program.cs
> +                    {
Пустой `else`?

2021-11-18 18:13 UTC, Tauders commented on Subtasks/Denis/Subtask-2/Program.cs
> +                if ((action == "+") | (action == "-") | (action == "*") | (action == "/"))
Почитай про "|" и "||" - там есть разница.

2021-11-18 18:13 UTC, Tauders commented on Subtasks/Denis/Subtask-2/Program.cs
> +                    if (numbers[index] == valuesOfNumbers[index])
Таких условий не было в задании, откуда они взялись?

2021-11-18 18:13 UTC, Tauders commented on Subtasks/Denis/Subtask-2/Program.cs
> +                    Console.WriteLine("Действие не выбрано");
Не совсем правильно написано - "Данное действие не поддерживается" или "Введено некорректное действие"

2021-11-18 18:13 UTC, Tauders commented on Subtasks/Denis/Subtask-2/Program.cs
> +            while (true)
А что, если ввести всё же неправильное действие?

2021-11-18 18:13 UTC, Tauders commented on Subtasks/Denis/Subtask-2/Program.cs
> +            int result = GetAction(action, valuesOfNumbers);
А где надпись, как в примере? Почему такое название функции?

2021-11-18 18:13 UTC, Tauders commented on Subtasks/Denis/Subtask-3/Subtask-3/Program.cs
> +            Console.WriteLine("Hello World!");
Зачем в ветке для задачи 2 задача 3?

2021-11-18 18:21 UTC, CodingFeles commented on Subtasks/Denis/Subtask-3/Subtask-3/Program.cs
> +            Console.WriteLine("Hello World!");
@morgunovdv удоли.

2021-11-23 06:25 UTC, Tauders requested changes

2021-11-23 06:25 UTC, Tauders commented on Subtasks/Denis/Subtask-2/Program.cs
> +                    string value = Convert.ToString(inputNumber[i]);
А если число будет 2 и более значным?

2021-11-23 06:25 UTC, Tauders commented on Subtasks/Denis/Subtask-2/Program.cs
> +                    break;
Чисто, как упражнение, попробуй сделать это же действие, без `break`, если будет непонятно, как, спрашивай.

2021-11-23 06:25 UTC, Tauders commented on Subtasks/Denis/Subtask-2/Program.cs
> +                    break;
Попробуй сделать это без `break` как упражнение.

2021-11-27 17:50 UTC, CodingFeles requested changes

2021-11-27 17:50 UTC, CodingFeles commented on Subtasks/Denis/Subtask-2/Program.cs
> +                        int number = Convert.ToInt32(tempNumbers[i]);
Нужна проверка на то, число ли это.

2021-11-27 17:50 UTC, CodingFeles commented on Subtasks/Denis/Subtask-2/Program.cs
> +            while ((action != "+") || (action != "-") || (action != "*") || (action != "/"))
Переделать условия while/if. Избавиться от дублирования.

2021-12-02 16:13 UTC, Tauders requested changes

2021-12-02 16:13 UTC, Tauders commented on Subtasks/Denis/Subtask-2/Program.cs
> +                            }
Много конвертаций, попробуй уменьшить.

2021-12-06 11:01 UTC, Tauders requested changes

2021-12-06 11:01 UTC, Tauders commented on Subtasks/Denis/Subtask-2/Program.cs
> +            while (action == null)
Не проще ли заменить флагом булевым? 
В том плане, что тебе не важно значение `action`, а важен только факт заполненности.

2021-12-06 11:01 UTC, Tauders commented on Subtasks/Denis/Subtask-2/Program.cs
> +                            }
Всё ещё лишние конвертации, а вот это
```
!Int32.TryParse(tempNumbers[tempIndex], out _)
```
максимально интересная проверка.

Посмотри на другой тип цикла, на всякий случай: https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/statements/iteration-statements#the-do-statement

Может пригодится.

2021-12-08 13:26 UTC, CodingFeles submitted a review, later dismissed

2021-12-08 15:09 UTC, CodingFeles approved these changes

2021-12-11 07:28 UTC, Tauders requested changes

2021-12-11 07:28 UTC, Tauders commented on Subtasks/Denis/Subtask-3/global.json
> +{
Зачем здесь этот файл?

2021-12-11 10:11 UTC, CodingFeles commented on Subtasks/Denis/Subtask-3/global.json
> +{
Лол, я его проглядел.

2021-12-12 10:40 UTC, Tauders approved these changes

2021-12-13 09:54 UTC, CodingFeles approved these changes

2021-12-13 09:54 UTC, merged