[Denis/Subtask - 3] Восстановление задачи
Tauders/dratuIT pull request #27
Opened 2021-12-09 05:23 UTC by morgunovdv

2021-12-11 08:12 UTC, Tauders requested changes

2021-12-11 08:12 UTC, Tauders commented on Subtasks/Denis/Subtask-3/Subtask-3/Program.cs
> +        public static List<string> GetSort(string method, List<string> words)
Лучше более говорящее: `GetSortedList` или типа того, но нужен ли тебе возврат данных?

2021-12-11 08:12 UTC, Tauders commented on Subtasks/Denis/Subtask-3/Subtask-3/Program.cs
> +                    GetSort(method, words);
Либо используй возврат данных, и убери изменение первоначального массива, либо меняй название и оставь использование, как есть.

2021-12-11 08:12 UTC, Tauders commented on Subtasks/Denis/Subtask-3/Subtask-3/Subtask-3.csproj
> +    <TargetFramework>net6.0</TargetFramework>
Если ничего особого из `net 6` не используешь, откати, плиз, на 5 версию, а то у нас используется Visual Studio 2019, в основном, не хочется держать 2 студии.

2021-12-12 07:28 UTC, Tauders requested changes

2021-12-12 07:28 UTC, Tauders commented on Subtasks/Denis/Subtask-3/Subtask-3/Program.cs
> +        public static void GetSortList(string method, List<string> words)
Что этот метод возвращает? `GetSortedList` (у тебя `GetSortList`, что звучит хуже, так как перевод "ПолучитьСортироватьСписок") подразумевает "ПолучитьСортированныйСписок" и обычно подразумевается получить на выходе, как возвращаемый параметр. У тебя же этого нет, так что `SortListByMethod` или типа того будет лучше.

2021-12-12 16:00 UTC, Tauders approved these changes

2021-12-12 16:00 UTC, Tauders commented on Subtasks/Denis/Subtask-3/Subtask-3/Program.cs
> +                    Console.WriteLine("Данное действие не поддерживается");
Добавь описание подсказки, типа "Введите действие ещё раз"

2021-12-13 09:59 UTC, CodingFeles approved these changes
isExit и isSelect - немного смущают с точки зрения английского языка, но не являются критичными замечаниями. 
Если именовать в том же виде, но чуть корректнее, то мне кажется, что hasExited, hasBeenSelected/isSelected были бы получше.
Но я бы везде пользовался словом done - "готово" или подобными аналогами.

2021-12-21 04:26 UTC, Tauders approved these changes

2021-12-21 05:07 UTC, merged