Denis/subtask 4
Tauders/dratuIT pull request #28
Opened 2021-12-21 15:08 UTC by morgunovdv

2022-01-14 17:12 UTC, Tauders requested changes

2022-01-14 17:12 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Group.cs
> +    internal class Group
Зачем этот файл?

2022-01-14 17:12 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Person.cs
> +    internal class Person
Зачем этот файл?

2022-01-14 17:12 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +        public static void SortingValues(string method, KeyValuePair<string, List<string>> groups)
Неправильное название, может `SortKeyValueValues` лучше?

2022-01-14 17:12 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                        string key = null;
Почему `key`, а другое `name`? Не `key/value`, не `group/name`?

2022-01-14 17:12 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            Console.WriteLine("Выбирите метод сортировки");
Опечатка: выберите

2022-01-14 17:12 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            string method = Console.ReadLine();
А если ввести не тот метод, который надо?

2022-01-15 07:39 UTC, Tauders requested changes
У тебя выведтся "такой команды нету", а затем словарь неотсортированный, немного странное поведение.

2022-01-15 07:39 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                    Console.WriteLine("Такой команды нету");
Не очень хорошая идея делать отображение пользователю из "левой", сугубо технической команды. Лучше сделать какую-то проверку до или вне метода

2022-01-19 16:44 UTC, Tauders submitted a review, later dismissed
В целом всё хорошо, комменты можем обсудить, если тебе интересны улучшения.

2022-01-19 16:44 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            bool isSelect = false;
Имя не очень.

2022-01-19 16:44 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            bool isExit = false;
Имя не очень.

2022-01-19 16:44 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                    foreach (KeyValuePair<string, List<string>> keyValuePair in groups)
Можно поменять `keyValuePair ` на `group`.

2022-01-19 16:44 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +        public static void SortKeyValueValues(string method, KeyValuePair<string, List<string>> groups)
Если твоя функция поддерживает только 2 этих метода (всегда и в обязательном порядке), то можно сделать, чтобы на вход применялся `Enum`, который содержит только 2 этих способа.

В текущей версии можно выбрасывать исключение в случае `default`, так как метод работает только в обозначенных условиях и иначе никак.

2022-01-20 14:10 UTC, CodingFeles requested changes
В целом - хорошо, но хочется увидеть использование Enumeration:

1.  Объяви перечисление.
2.  Сделай функцию перевода строки в значение перечисления.
3.  Используй эти значения перечисления для выбора нужного способа сортировки.

2022-01-20 14:10 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +        public static void SortKeyValueValues(string method, KeyValuePair<string, List<string>> groups)
Да, одна из полезных "привычек", точнее, скорее подходов: всегда, когда есть ограниченное множество каких-то специальных значений: типы чего-то, режимы, методы и т.п. - стоит описывать Enumeration'ы - "перечисления".

И даже с Enum'ами, стоит оставлять дефолтную ветку и бросать в ней исключение (если по логике нет дефолтного поведения) - так как эти Enum'ы могут со временем расширяться и это исключение поможет найти место, где забыли добавить обработку нового значения.

2022-01-20 14:10 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            bool isExit = false;
+

2022-01-20 14:10 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            bool isSelect = false;
+

2022-01-20 14:10 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                    foreach (KeyValuePair<string, List<string>> keyValuePair in groups)
Я бы использовал var, вместо KeyValuePair<,> и да, group или обобщённое item выглядело бы получше.

2022-01-21 17:14 UTC, CodingFeles requested changes
Привнёс нужные изменения, но тут же добавил несколько вещей, которые стоит делать по другому. Что хорошо: заодно поучишься как делать не стоить.

2022-01-21 17:14 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +        public static void PrintResult (string method, SortingMethod sorting, Dictionary<string, List<string>> groups)
Зачем тебе входной аргумент sorting, если ты его только тут получаешь?

2022-01-21 17:14 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +        public static void PrintResult (string method, SortingMethod sorting, Dictionary<string, List<string>> groups)
sorting - было бы лучше обозвать method.
И перевод строки в SortingMethod было бы лучше сделать в отдельном методе, который бы принимал строку, а возвращал значение SortingMethod.

2022-01-21 17:14 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                Console.WriteLine("Исходный вариант словаря");
Co to je?

2022-01-21 17:14 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> -                default:
Зачем ты убрал дефолт? Мы же обсуждали в прошлом ревью, что, наоборот, он нужен.

2022-01-21 17:14 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            if ((method == "asc") || (method == "1"))
Поддержать и текстовой, и номерной вариант - хорошая идея.

2022-01-21 17:14 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            PrintResult(method, sorting, groups);
Метод PrintResult должен заниматься только выводом результата.
Он не должен и переводить строку в значение Enum'а, сортировать и к этому уже делать вывод.
Логически разбивай разные действия на разные методы.

2022-01-26 08:40 UTC, Tauders requested changes
Разбей программу на несколько файлов, как минимум вынеси енум в отдельный файл.

2022-01-26 08:40 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            undefined
Обычно именование значений енумов происходит с большой буквы.

Ещё момент - обычно значение "по умолчанию" ставится первым и ему присваивается значение 0, так как оно будет дефолтным в случае создания енума.

Зачем здесь есть переменная exit? Какое это имеет отношение к методам сортировки?

2022-01-26 08:40 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            if ((method == "asc") || (method == "1"))
Я считаю плохой идеей разрешать такой ввод, @CodingFeles нафига это надо?

2022-01-26 08:40 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +        public static SortingMethod ConvertInput(string method)
Посмотри на метод для парсинга enum. Спойлер - в гугле `Convert string to enum c#`

2022-01-26 08:40 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                    break;
Зачем он нужен, если default делает тоже самое?

2022-01-26 08:40 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            Console.WriteLine("Выберите метод сортировки: \n1. asc (сортировка по возрастанию) \n2. desc (сортировка по убыванию) \n3. exit (вывести исходный словарь)");
Длинная строка, сделай короче.

2022-01-26 08:40 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            SortingMethod sorting = 0;
Почему не 
```cs
            SortingMethod sorting = SortingMethod.undefined;
```
?

2022-01-26 08:40 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            bool isUndefined = false;
Если "неНеопределенно" ложь, то значит определенно? 
И как только результат становится неопределённым, то цикл закончился?

2022-01-26 08:42 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                Console.WriteLine("По возрастанию");
Не добавляй в "технические" методы взаимодействие с пользователями

2022-01-26 08:42 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                SortKeyValueValues(sorting, group);
Почему отображение (судя по названию метода) ещё и сортирует?

2022-01-27 13:22 UTC, Tauders requested changes

2022-01-27 13:22 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +
Зачем лишние переносы?

2022-01-27 13:22 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                    if(Enum.IsDefined(typeof(SortingMethod), sorting))
Зачем эта проверка нужна? Ты же уже имеешь значение на этот момент.

2022-01-27 13:22 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                    sorting = SortingMethod.Undefined;
А зачем эта установка?

2022-01-27 13:22 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                    Console.WriteLine("По возрастанию");
Убери от "технических" методов вывод на консоль.
Представь, что потом этот же метод захотят использовать в другом месте - в вебе, например, на сервере. Но там вывод в консоль не имеет никакого смысла.

2022-01-27 13:22 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            bool isExit = false;
+

2022-01-27 13:22 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                    if (input.ToUpper() == "X")
Здесь это норм, но можешь посмотреть интереса ради на функцию 
https://docs.microsoft.com/ru-ru/dotnet/api/system.string.equals?view=net-6.0#system-string-equals(system-string-system-stringcomparison)

2022-01-27 13:22 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +
Лишний перенос строки.

2022-01-27 13:22 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                        for (int i = 0; i < temp.Length; i++)
А нужен ли здесь цикл?

2022-01-27 13:22 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            Console.WriteLine("Выберите метод сортировки: \n1. Asc \n2. Desc");
Может проще написать несколько `Console.WriteLine`, чем городить переносы строк через `\n`?

2022-01-27 13:22 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            bool isUndefined = true;
Имя так себе.

2022-01-27 13:22 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/SortingMethod.cs
> +        Asc = 1,
Лучше всё же поменять `Undefined` и `Asc` местами и начать нумерацию с 0 - так будет понятно, что дефолтное значение это "неопределенно" + есть случаи, когда создаётся без явное иницализации и тогда с текущим подходом могут быть проблемы с значением по умолчанию.

2022-01-27 14:17 UTC, CodingFeles requested changes
Отлично. Теперь у нас есть грамотная работа с Enum'ом. Выглядит здорово.
Осталось отработать небольшие замечания и подумать над ситуацией с лишними пробелами в пользовательском вводе.

2022-01-27 14:17 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +
Зачем лишние переносы?

2022-01-27 14:17 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                default:
Мы тебе писали в прошлых ревью, что здесь стоит бросать ошибку.  У тебя нет действия по умолчанию для сортировки массива: ты либо его в одном направлении сортируешь, либо в другом.

2022-01-27 14:17 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            bool isExit = false;
+

2022-01-27 14:17 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                        string[] temp = input.Split(' ', StringSplitOptions.RemoveEmptyEntries);
Как быть, если пользователь опечатается и введёт лишний пробел? Что дальше будет делать программа и желаемое ли это поведение для пользователя?

2022-01-27 14:17 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            bool isUndefined = true;
Почему так себе? В плане нотаций именнований: isAdjective для bool - норм.
По английски тоже корректно.
Можно уточнить в названии, что именно метод не определён, но, имхо, и так норм.

Я бы, вообще, использовал значение переменной sorting тут :)

2022-01-27 14:17 UTC, Tauders requested changes

2022-01-27 14:17 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/SortingMethod.cs
> +        Undefined,
Верни числовое обозначение - обычно это хорошая практика, так как сериализация и десериализация сможет опираться на эти числовые значение

2022-01-27 14:19 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            bool isUndefined = true;
Просто звучит странно, может чуть определённее, типа `isSortingUndefined` или вообще не заводить, да.

2022-01-27 16:01 UTC, morgunovdv commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                        string[] temp = input.Split(' ', StringSplitOptions.RemoveEmptyEntries);
норм же обрабатывает. Он все пробелы убирает

2022-01-27 16:47 UTC, morgunovdv commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                default:
а если например 3 не дано)) либо сортировка либо уведомление о том что не выбран метод?

2022-01-27 16:48 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                default:
Бросай исключение

2022-01-28 09:44 UTC, Tauders requested changes

2022-01-28 09:44 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            }
Верни случай `default` и сделай там выбрасывание исключения.

2022-01-28 09:44 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +        public static SortingMethod DefineMethod(SortingMethod method)
Что это и зачем?

2022-01-28 09:44 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                        sorting = sortingMethod;
Зачем? Используй напрямую sorting.

2022-01-29 21:17 UTC, Tauders requested changes

2022-01-29 21:17 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                    Console.WriteLine("Данного метода не существует. Повторите ввод");
Убери дублирование.

2022-01-29 21:17 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            bool isExit = false;
+

2022-01-29 21:17 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                        string[] temp = input.Split(' ', StringSplitOptions.RemoveEmptyEntries);
Переименуй по смыслу

2022-01-29 21:25 UTC, CodingFeles requested changes

2022-01-29 21:25 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                default:
Дали прямую рекомендацию: бросать ошибку, точнее исключение. Я не вижу этого исправления.

2022-01-29 21:25 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +            bool isExit = false;
+

2022-01-29 21:25 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/SortingMethod.cs
> +        Asc,
Стоит числовой эквивалент тогда всем значениям выставить.

2022-01-29 21:25 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                        if(temp.Length > 1)
"Нар ды Пельменеед". Ну, ты понел.

2022-02-02 09:33 UTC, Tauders requested changes

2022-02-02 09:33 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                    Console.WriteLine("Данного метода не существует. Повторите ввод");
Убери `Console.WriteLine`, бросай исключение, не закрывай комментарии, которые не поправлены.

2022-02-02 09:33 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +        }
Зачем так сложно?

2022-02-02 09:33 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                            Console.WriteLine("Допушена ошибка при вводе");
Допущена*

2022-02-02 09:33 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +        public static SortingMethod test(string input)
Название 10 из 10

2022-02-02 10:10 UTC, morgunovdv commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +        public static SortingMethod test(string input)
бля) забыл поправить)))

2022-02-02 10:11 UTC, Tauders requested changes

2022-02-02 10:11 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                        string[] KeyValuePairs = input.Split(' ', StringSplitOptions.RemoveEmptyEntries);
Почему с большой буквы?

2022-02-02 11:30 UTC, Tauders requested changes

2022-02-02 11:30 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                        }
Переработай, упрости, можно убрать проверку 1.

2022-02-02 11:38 UTC, Tauders requested changes

2022-02-02 11:38 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                        if ((keyValuePairs.Length < 2) || (keyValuePairs.Length > 2))
`!= 2` будет проще понять

2022-02-02 11:56 UTC, Tauders requested changes

2022-02-02 11:56 UTC, Tauders commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                        string group = null;
А зачем эти переменные нужны здесь?

2022-02-02 13:45 UTC, Tauders approved these changes

2022-02-02 17:33 UTC, CodingFeles requested changes
В целом, всё хорошо, но ```if(sorting == SortingMethod.Undefined)``` мне не нравится. Надо доправить и можно считать работу завершённой.

2022-02-02 17:33 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                        string[] keyValuePairs = input.Split(' ', StringSplitOptions.RemoveEmptyEntries);
Почему pairs, когда пара одна?

2022-02-02 17:33 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                if(sorting == SortingMethod.Undefined)
Зачем здесь отдельная проверка на то, какой метод, если у тебя есть конкретное место, где это можно понять просто по факту того, что в это место зашло исполнение кода?

2022-02-02 17:53 UTC, CodingFeles submitted a review, later dismissed
Осталось два замечания (один больше комментарий, а не замечание). Я не считаю, что их обязательно надо исправлять, но будет бонусом если попробуешь. 
Считаю задачу выполненной.

2022-02-02 17:53 UTC, CodingFeles commented on Subtasks/Denis/Subtask-4/Subtask-4/Program.cs
> +                if(sorting == SortingMethod.Undefined)
Я неправильно понял ситуацию. Комментарий остаётся, так как всё ещё можно переделать код, чтобы не требовалась отдельная проверка в конце.
Но запрос на исправить я отзываю. Останется как замечание. Если интересно, то попробуй исправить.

2022-02-03 09:31 UTC, Tauders approved these changes

2022-02-03 09:36 UTC, CodingFeles approved these changes

2022-02-03 09:49 UTC, merged