Denis/subtask 5
Tauders/dratuIT pull request #32
Opened 2022-02-03 07:10 UTC by morgunovdv

2022-02-04 10:52 UTC, Tauders requested changes

2022-02-04 10:52 UTC, Tauders commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                        }
А почему не в 1 цикл?

2022-02-04 10:52 UTC, Tauders commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                        double midNumber = Math.Round((result / uniqueValues.Count),1);
Зачем это вычисляется здесь?

2022-02-04 10:52 UTC, Tauders commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                        Console.WriteLine($"\nМинимальное значение = {min}");
Не используй `\n` - если хочешь сделать перенос, то используй `Environment.NewLine`

2022-02-04 10:52 UTC, Tauders commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                            Console.Write(number +" ");
Используй интерполяцию.

2022-02-04 10:52 UTC, Tauders commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +            {
А уменьши ка этот цикл.

2022-02-04 10:52 UTC, Tauders commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                        List<int> uniqueValues = distincrNumber.ToList();
Попробуй другую коллекцию - хеш-таблицу. И её разновидность HashSet.

2022-02-04 18:44 UTC, CodingFeles requested changes

2022-02-04 18:44 UTC, CodingFeles commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                string inputNumberLenth = Console.ReadLine();
Опечатка в названии переменной.

2022-02-04 18:44 UTC, CodingFeles commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                if (int.TryParse(inputNumberLenth, out int numbersLenth))
Аналогичная опечатка в названии у другой переменной.

2022-02-04 18:44 UTC, CodingFeles commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                            isNotError = false;
Допустим, у тебя 1000 чисел. Тебе тысячу раз надо выставлять isNotError в false?

2022-02-04 18:44 UTC, CodingFeles commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                        IEnumerable<int> distincrNumber = numbers.Distinct();
Опечатка.

2022-02-04 18:44 UTC, CodingFeles commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                        Console.WriteLine($"\nМинимальное значение = {min}");
И тогда уж, сделал перенос строки отдельным выводом. Как-то не очень эстетично вмазывать его вперёд сообщения на новой строке.

2022-02-04 18:44 UTC, CodingFeles commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                    Console.WriteLine("Вы указали данные в другом формате");
А какой формат ожидался? Вроде, формата особо и нет, просто число хотим.

2022-02-05 17:05 UTC, Tauders requested changes

2022-02-05 17:05 UTC, Tauders commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                        int min = numbers.SelectMany(min => numbers).Min();
Верни способ, как считал раньше

2022-02-05 17:05 UTC, Tauders commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                        isNotError = false;
Перенеси выше, чтобы было хоть чуть логично.

2022-02-05 17:05 UTC, Tauders commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                {
Уменьши цикл! Не убирай комменты, которые не поправил!

2022-02-05 20:12 UTC, morgunovdv commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                        double midNumber = Math.Round((result / uniqueValues.Count),1);
не понял вопроса

2022-02-05 20:13 UTC, Tauders requested changes

2022-02-05 20:13 UTC, Tauders commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +            while (isNotError)
Вариант имени инверсивный (не ошибка) читать не очень хорошо, поменяй на прямой

2022-02-05 20:14 UTC, Tauders commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                        double midNumber = Math.Round((result / uniqueValues.Count),1);
Раньше было какое-то странное место

2022-02-05 20:15 UTC, Tauders requested changes
Отфроматируй документ

2022-02-05 20:15 UTC, Tauders commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +            int min = 0;
Если ты хочешь, чтобы у минимального значения стояло по умолчанию большое число, то используй `int.MaxValue`

2022-02-05 20:15 UTC, Tauders commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                }
Можно упростить, если задать изначально `min`.

2022-02-06 07:20 UTC, Tauders requested changes

2022-02-06 07:20 UTC, Tauders commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                        Console.WriteLine("Введенное вами число вне диапозона");
`диапазона`

2022-02-06 07:20 UTC, Tauders commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +            while (isError)
Странновато звучит, по умолчанию ошибка?

2022-02-06 07:20 UTC, Tauders commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +                    if ((numbersLength < 10) || (numbersLength > 1000))
А 10 или 1000 нельзя ввести?

2022-02-06 07:20 UTC, Tauders commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +            double result = 0;
А зачем double?

2022-02-06 07:32 UTC, Tauders approved these changes

2022-02-06 10:40 UTC, CodingFeles approved these changes
За исключением пары не лучших названий переменных, всё хорошо.

2022-02-06 10:40 UTC, CodingFeles commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +            bool isUnknownNumber = true;
Такое себе название переменной.

2022-02-06 10:40 UTC, CodingFeles commented on Subtasks/Denis/Subtask-5/Subtask-5/Program.cs
> +            double midNumber = Math.Round(((double)result / numbers.Count), 1);
midNumber - это не арифметическое среднее.

2022-02-06 14:43 UTC, merged